#!/usr/bin/env python

from boto3 import session
from botocore.exceptions import ClientError

import tarfile
import io
import os


# Application parameters
name = os.getenv("APP_NAME")
version = os.getenv("APP_VERSION")
instance = os.getenv("APP_INSTANCE", None)
configpath = os.getenv("APP_CONFIGPATH", "config/configuration.json")

target = "dist"

print("INFO %s %s %s %s" % (name, version, instance, configpath))


# Create S3 client
client = session.Session().client("s3",
    region_name="fra1",
    endpoint_url="https://fra1.digitaloceanspaces.com",
    aws_access_key_id=os.getenv("DO_SPACES_KEY"),
    aws_secret_access_key=os.getenv("DO_SPACES_SECRET")
    )


# Unpack static site
try:
    response = client.get_object(
        Bucket="scriptum-assets",
        Key="packages/%s/%s" % (name, version),
    )
except ClientError as ex:
    print("ERROR: Couldn't get version '%s' for '%s'" % (version, name))
    os.sys.exit(1)
with tarfile.open(fileobj=response["Body"], mode="r:gz") as tar:
    tar.extractall(target)

# Get configuration file (if any)
if instance:
    print("Downloading packages/%s/%s into %s/%s" % (name, instance, target, configpath))
    if '/' in configpath:
        os.makedirs(os.path.join(target, os.path.dirname(configpath)), exist_ok=True)
    try:
        client.download_file(
            "scriptum-assets",
            "packages/%s/%s" % (name, instance),
            "%s/%s" % (target, configpath)
            )
    except ClientError as ex:
        print("ERROR: Couldn't get configuration for packages/%s/%s" % (name, instance))
        os.sys.exit(1)


print("Succesful deploy")
