#!/usr/bin/env python

from boto3 import session
from botocore.exceptions import ClientError

import tarfile
import io
import os


# Application parameters
name = os.getenv("APP_NAME")
version = os.getenv("APP_VERSION")
instance = os.getenv("APP_INSTANCE")

target = "dist"


# Create S3 client
client = session.Session().client("s3",
    region_name="fra1",
    endpoint_url="https://fra1.digitaloceanspaces.com",
    aws_access_key_id=os.getenv("SECRET_DO_SPACES_KEY"),
    aws_secret_access_key=os.getenv("SECRET_DO_SPACES_SECRET")
    )


# Get configuration file
os.makedirs("%s/config" % target, exist_ok=True)
try:
    client.download_file(
        "scriptum-assets",
        "packages/%s/%s" % (name, instance),
        "%s/config/configuration.json" % target
        )
    print("DOWNLOADED packages/%s/%s into %s" % (name, instance, target))
except ClientError as ex:
    print("ERROR: Couldn't get configuration for %s" % name)
    os.sys.exit(1)


# Unpack static site
try:
    response = client.get_object(
        Bucket="scriptum-assets",
        Key="packages/%s/%s" % (name, version),
    )
    print("DOWNLOADED packages/%s/%s" % (name, version))
except ClientError as ex:
    print("ERROR: Couldn't get version '%s' for '%s'" % (version ,name))
    os.sys.exit(1)
with tarfile.open(fileobj=response["Body"], mode="r:gz") as tar:
    tar.extractall(target)
    for member in tar.getmembers():
        print("Extracted:", member.name)
